server:
  port: 8090
  servlet:
    context-path: /order

spring:
  application:
    name: shop-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  cloud:
    nacos:
      discovery:
        server-addr: 10.32.1.100:8848

    sentinel:
      transport:
        port: 9999 # 指定和 sentinel 控制台交互的端口，任意指定一个未使用的端口即可
        dashboard: 10.32.1.100:8888 # sentinel 控制太服务地址

# 开启 Feign 对 sentinel的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  global-config:
    db-config:
      table-underline: true
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: 'null'
